FreshMart/Areas/Admin/Controllers/AdminAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreshMart.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace FreshMart.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminAccountController : Controller
    {
        [Route("Admin/AdminAccount")]

        public IActionResult SignIn()
        {

            return View();
        }


        [Route("Admin/AdminAccount")]
        [HttpPost]
        public IActionResult SignIn(AccountViewModel account)
        {



            if (account.Username == "Admin" && account.Password == "Admin")
            {


                return RedirectToAction("Index", "Home", new { area = "Admin" });
            }
            else
            {
                return View();
            }

        }
    }
}

FreshMart/Areas/Admin/Views/AdminAccount/SignIn.cshtml
@model FreshMart.ViewModels.AccountViewModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";

}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE 2 | Log in</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/lib/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    @*<link rel="stylesheet" href="~/AdminComponents/bower_components/Ionicons/css/ionicons.min.css">*@
    <!-- Theme style -->
    <link rel="stylesheet" href="~/AdminComponents/dist/css/AdminLTE.min.css">

</head>

<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="../../index2.html"><b>Admin&nbsp;</b>LOGIN</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            @* <p class="login-box-msg">Sign in to start your session</p> *@

            @using (Html.BeginForm("SignIn", "AdminAccount", FormMethod.Post))
            {

                @*                 <div asp-validation-summary="All" class="text-danger"></div> *@
                <div class="form-group has-feedback">
                    <label asp-for="Username">Username</label>
                    @Html.TextBoxFor(c => c.Username, new { @class = "form-control" })
                    <span asp-validation-for="Email" class="text-danger"></span>
                </div>
                <div class="form-group has-feedback">
                    <label asp-for="Password">Password</label>
                    @Html.PasswordFor(c => c.Password, new { @class = "form-control" })
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>


                <div class="row">

                    <!-- /.col -->
                    <div class="col-xs-4">
                        <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
                    </div>
                    <!-- /.col -->
                </div>
            }


        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    <!-- jQuery 3 -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <!-- Bootstrap 3.3.7 -->
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <!-- iCheck -->
    @* <script src="../../plugins/iCheck/icheck.min.js"></script> *@
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' /* optional */
            });
        });
    </script>
</body>

</html>