FreshMart/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace FreshMart.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        [Route("Admin/")]
        public IActionResult Index()
        {

            return View();
        }
    }
}

FreshMart/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreshMart.Core;
using FreshMart.Database;
using FreshMart.Helper;
using FreshMart.Models;
using FreshMart.ViewModels;
using FreshMart.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreshMart.Controllers
{

    public class CartController : Controller
    {
        //AppUser appUser;

        private readonly AppDbContext _context;
        private int cartCount;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IProductService _productService;
        public CartController(AppDbContext con, IHttpContextAccessor hca, IProductService productService)
        {
            _context = con;
            _httpContextAccessor = hca;
            _productService = productService;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        [Route("/Cart")]
        public async Task<ActionResult> Cart()
        {
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                ViewBag.Message = "Your Cart Is Empty";
                this.cartCount = 0;
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;
                this.cartCount = cart.Count;
                ViewBag.total = cart.Sum(c => c.Product.Price * c.Quantity);
            }
            var viewmodel = await _productService.GetProductViewModelAsync();

            ViewBag.CartCount = this.cartCount;
            return View(viewmodel);
        }


        [Route("Cart/addtocart/{id}")]
        public ActionResult AddToCart(long id)
        {
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                var cart = new List<CartItem>();
                var item = new CartItem
                {
                    Product = _context.Products.Where(x => x.Id == id).Include(x => x.Photo).AsEnumerable().Select(x =>
                    {
                        if (x.Photo != null)
                        {
                            x.Photo.Path = "https://localhost:44318" + x.Photo.Path;
                        }
                        return x;
                    }).FirstOrDefault(),
                    Quantity = 1
                };
                cart.Add(item);

                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                var sessiondata = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                int index = Exists(cart, id);
                if (index == -1)
                {
                    var item = new CartItem
                    {
                        Product = _context.Products.Where(x => x.Id == id).Include(x => x.Photo).AsEnumerable().Select(x =>
                       {
                           if (x.Photo != null)
                           {
                               x.Photo.Path = "https://localhost:44318" + x.Photo.Path;
                           }
                           return x;
                       }).FirstOrDefault(),
                        Quantity = 1,

                    };
                    cart.Add(item);
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction(nameof(Cart));
        }

        [Route("Cart/RemoveItem/{id}")]
        public ActionResult RemoveItem(long id)
        {

            var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return RedirectToAction(nameof(Cart));
        }

        //local function start
        private int Exists(List<CartItem> cart, long id)
        {
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
        //local function end

    }
}

FreshMart/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using FreshMart.Models;
using Microsoft.EntityFrameworkCore;
using FreshMart.Helper;
using Microsoft.AspNetCore.Http;
using FreshMart.Services;
using FreshMart.Database;
using FreshMart.ViewModels;
using FreshMart.Core;

namespace FreshMart.Controllers
{
    public class HomeController : Controller
    {


        private readonly AppDbContext _context;
        private IHttpContextAccessor _httpContextAccessor;
        private int cartCount;
        private CartService cs;
        public HomeController(AppDbContext con, IHttpContextAccessor hca)
        {
            _context = con;
            _httpContextAccessor = hca;
            cs = new CartService(hca, con);
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }

        [Route("/{msg?}")]
        public async Task<IActionResult> Index(string msg)
        {
            string a = "";
            if (msg != null)
            {
                a = "Success";
            }


            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                this.cartCount = 0;
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                this.cartCount = cart.Count;
            }



            var products = _context.Products
               .Include(c => c.Category)
               .Include(c => c.District)
               .Include(x => x.Photo)
               .AsEnumerable().Select(x =>
               {
                   if (x.Photo != null)
                   {
                       x.Photo.Path = "https://localhost:44318" + x.Photo.Path;
                   }

                   return x;
               });

            var categories = await _context.Categories.Where(x => !x.IsParent).AsNoTracking().ToListAsync();
            var districts = await _context.Districts.AsNoTracking().ToListAsync();
            var domains = await _context.Categories.Where(x => x.IsParent).AsNoTracking().Select(c => c.Name).ToListAsync();


            var productView = new ProductViewModel
            {
                Products = products.ToList(),
                Category = categories,
                District = districts,
                DistinctCat = domains,
                CartCount = this.cartCount,
                TotalPrice = cs.GetCartTotalPrice(),
                Message = a,
                Sellers = await _context.Sellers.AsNoTracking().ToListAsync(),
                Customers = await _context.Customers.AsNoTracking().ToListAsync(),

            };

            return View(productView);
        }


        [Route("/Home/About")]
        public async Task<IActionResult> About()
        {
            ViewData["Message"] = "Your application description page.";


            var categories = await _context.Categories.Where(x => !x.IsParent).ToListAsync();
            var districts = await _context.Districts.ToListAsync();
            var parents = await _context.Categories.Where(x => x.IsParent).Select(c => c.Parent.Name).Distinct().ToListAsync();

            var cartCount = cs.GetCartCount();
            var productView = new ProductViewModel
            {
                Category = categories,
                District = districts,
                DistinctCat = parents,
                CartCount = cartCount,
                TotalPrice = cs.GetCartTotalPrice(),
                Sellers = await _context.Sellers.ToListAsync()
            };




            return View(productView);
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        [Route("Home/Faq")]
        public IActionResult Faq()
        {

            ViewData["Message"] = "Your application Faq page.";


            var categories = _context.Categories.ToList();
            var districts = _context.Districts.ToList();
            var domains = _context.Categories.Where(x => x.ParentId != null).Select(c => c.Parent.Name).Distinct().ToList();

            var cartCount = cs.GetCartCount();
            var productView = new ProductViewModel
            {
                Category = categories,
                District = districts,
                DistinctCat = domains,
                CartCount = cartCount,
                TotalPrice = cs.GetCartTotalPrice(),
                Sellers = _context.Sellers.ToList()
            };


            return View(productView);
        }


        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FreshMart/Views/Home/About.cshtml
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

<!-- banner -->
<div class="banner10" id="home1">
    <div class="container">
        <h2>About Us</h2>
    </div>
</div>
<!-- //banner -->
<!-- about -->
<div class="about">
    <div class="container">
        <div class="w3ls_about_grids">
            <div class="col-md-6 w3ls_about_grid_left">
                <p>
                    Duis aute irure dolor in reprehenderit in voluptate velit esse
                    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
                    cupidatat non proident, sunt in culpa qui officia deserunt mollit
                    anim id est laborum.
                </p>
                <div class="col-xs-2 w3ls_about_grid_left1">
                    <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
                </div>
                <div class="col-xs-10 w3ls_about_grid_left2">
                    <p>
                        Sunt in culpa qui officia deserunt mollit
                        anim id est laborum.Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur.
                    </p>
                </div>
                <div class="clearfix"></div>
                <div class="col-xs-2 w3ls_about_grid_left1">
                    <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>
                </div>
                <div class="col-xs-10 w3ls_about_grid_left2">
                    <p>
                        Sunt in culpa qui officia deserunt mollit
                        anim id est laborum.Duis aute irure dolor in reprehenderit in voluptate velit esse
                        cillum dolore eu fugiat nulla pariatur.
                    </p>
                </div>
                <div class="clearfix"></div>
            </div>
            <div class="col-md-6 w3ls_about_grid_right">
                <img src="images/77.jpg" alt=" " class="img-responsive" />
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- //about -->

FreshMart/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

FreshMart/Views/Home/Faq.cshtml
@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}


<!-- banner -->
@* <div class="banner10 mybanner" id="home1"> *@
@*     <div class="container"> *@
@*         <h2>Some Frequently Asked Questions</h2> *@
@*     </div> *@
@* </div> *@
<!-- //banner -->
<!-- about -->
<!-- //about -->
<!-- team -->
<div class="team">
    <div class="container">
        <h3>Hey, Learn Us, Stay Close</h3>
        <div class="wthree_team_grids">

            <div class="col-md-3 wthree_team_grid">
                <h4>What is FreshMArt? </h4>
                <div class="agileits_social_button" style="text-align: left; color: aliceblue">

                    FreshMart is a online market place that makes a connection between the user with the customer directly and makes a perfect
                    buying/selling environment.
                </div>
            </div>

            <div class="col-md-3 wthree_team_grid">
                <h4>How to sell a Product? </h4>
                <div class="agileits_social_button" style="text-align: left; color: aliceblue">
                    To sell a product You have to be a seller first ! Or you won't be able to sell any product here.
                    Give you necessary information to be a seller first.
                </div>
            </div>

            <div class="col-md-3 wthree_team_grid">
                <h4>How to buy a Product? </h4>
                <div class="agileits_social_button" style="text-align: left; color: aliceblue">
                    To buy a product You need to select your product and go for checkout ! Its super easy!
                    If you are a member you will get a little advantage to entry your details.
                </div>
            </div>
            <div class="col-md-3 wthree_team_grid">
                <h4>How to perfectly checkout product?</h4>
                <div class="" style="text-align: left; color: aliceblue">
                    To make a perfect checkout you need to follow the instraction below: <br />
                    <ul style="text-align: left; color: aliceblue">
                        <li>Input basic info</li>
                        <li>Make sure you paid total amount</li>
                        <li>If any mistake you can contact</li>
                    </ul>
                </div>
            </div>



            <div class="clearfix"></div>

        </div>
    </div>
</div>
<!-- //team -->
<!-- team-bottom -->
<div class="team-bottom">
    <div class="container">
        <h3>Are You Ready For Awesomeness? So Get Started Now !</h3>

        <a asp-controller="Products" asp-action="Index">Shop Now</a>
    </div>
</div>
<!-- //team-bottom -->

FreshMart/Views/Home/Index.cshtml
@model FreshMart.ViewModels.ProductViewModel

@{
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@{
    ViewData["Title"] = "Home Page";
}

<!-- banner -->
<div class="banner" id="home1">
    <div class="container">
        <h3>Fresh food for <span>Fresh Heart</span></h3>
    </div>
</div>
<!-- //banner -->


<div class="body-content" style=" margin: 0px;">

    <!-- new-products -->
    @*<div class="new-products">*@

    <div class="container">
        <br />
        <h2 class="text-center" style="color:#ff9659">Our Products</h2>

        <div class="agileinfo_new_products_grids">
            @{
                int count = 0;
            }
            @foreach (var items in Model.Products)
            {
                <div class="col-md-3 agileinfo_new_products_grid">
                    <div class="agile_ecommerce_tab_left agileinfo_new_products_grid1">
                        <div class="hs-wrapper hs-wrapper1">
                            <img src="@items.Photo?.Path" alt=" " class="img-responsive" />
                            <div class="w3_hs_bottom w3_hs_bottom_sub">
                                <ul>
                                    <li>
                                        <a href="#" data-toggle="modal" data-target="#myModal_@count">
                                            <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <h5><a href="single.html">Skirts</a></h5>
                        <div class="simpleCart_shelfItem">
                            <p> <i class="item_price">@items.Price</i></p>
                            @*<p><a class="item_add" href="#">Add to cart</a></p>*@
                            <p><a asp-controller="Cart" asp-action="addtocart" asp-route-id="@items.Id">Add to cart</a></p>
                        </div>
                    </div>
                </div>

                @*This is product detail modal start*@

                <div class="modal video-modal fade" id="myModal_@count" tabindex="-1" role="dialog"
                     aria-labelledby="myModal6">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <section>
                                <div class="modal-body">
                                    <div class="col-md-5 modal_body_left">
                                        <img src="@items.Photo?.Path" alt=" " class="img-responsive" />
                                    </div>
                                    <div class="col-md-7 modal_body_right">
                                        <h4>@items.Title</h4>
                                        <p>
                                            @items.Description
                                        </p>

                                        <div class="modal_body_right_cart simpleCart_shelfItem">
                                            <p> <i class="item_price">$@items.Price</i></p>
                                            <p><a class="item_add" href="#">Add to cart</a></p>
                                        </div>

                                    </div>
                                    <div class="clearfix"></div>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
                @*This is product detail modal end*@

                count++;

            }

            @if (Model.Products.Count == 0)
            {
                <div class="row">
                    <div class="col-md-12">
                        <h5 class="text-center">
                            There is no recent products to show
                        </h5>
                    </div>

                </div>
            }
            <div class="clearfix"></div>
        </div>
    </div>
</div>
<!-- //new-products -->
<!-- top-brands -->


@{
    var pro = Model.Products.Where(c => c.CreatedAt >= (DateTime.Now.AddDays(-5))).ToList();
    if (pro.Count > 0)
    {
        <div class="top-brands">
            <div class="container">
                <h3>Recently added Products</h3>

                @{

                    var p = Model.Products.Where(c => c.CreatedAt >= (DateTime.Now.AddDays(-5)));
                }

                <div class="sliderfig">
                    <ul id="flexiselDemo1">

                        @foreach (var items in p)
                        {
                            <li class="recent-products">
                                <img src=@items.Photo?.Path alt=" " class="img-responsive" />
                            </li>
                        }

                    </ul>
                </div>
                <script type="text/javascript">
                    $(window).load(function () {
                        $("#flexiselDemo1").flexisel({
                            visibleItems: 3,
                            animationSpeed: 1000,
                            autoPlay: true,
                            autoPlaySpeed: 3000,
                            pauseOnHover: true,
                            enableResponsiveBreakpoints: true,
                            responsiveBreakpoints: {
                                portrait: {
                                    changePoint: 480,
                                    visibleItems: 1
                                },
                                landscape: {
                                    changePoint: 640,
                                    visibleItems: 2
                                },
                                tablet: {
                                    changePoint: 768,
                                    visibleItems: 3
                                }
                            }
                        });

                    });
                </script>

                <script type="text/javascript" src="~/Assets/js/jquery.flexisel.js"></script>
            </div>
        </div>
    }
    else
    {
        <div class="top-brands">
            <div class="container">
                <h3>Recently added Products</h3>

                <div class="row">
                    <div class="col-md-12">
                        <h5 class="text-center">
                            There is no recent products to show
                        </h5>
                    </div>

                </div>
            </div>

        </div>

    }

}


<!-- //top-brands -->