FreshMart/Areas/Admin/Controllers/ProductManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FreshMart.Models;
using FreshMart.Database;
using FreshMart.Core;
using FreshMart.Core.Utilities;

namespace FreshMart.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductManagerController : Controller
    {
        private readonly AppDbContext _context;

        public ProductManagerController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Admin/ProductManager
        [Route("[area]/[controller]")]
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.Products.Include(p => p.Category).Include(p => p.District).Include(p => p.Seller);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Admin/ProductManager/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .Include(p => p.District)
                .Include(p => p.Seller)
                .SingleOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // GET: Admin/ProductManager/Create
        [Route("Admin/ProductManager/Create")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Domain");
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division");
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Email");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,SellerId,Price,Description,Unit,IsPublished,ItemInStock,DistrictId,CategoryId,ImagePath,OfferPrice,OfferExpireDate,CreatedAt,UpdatedAt")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.Id = NumberUtilities.GetUniqueNumber();
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Domain", product.CategoryId);
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division", product.DistrictId);
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Email", product.SellerId);
            return View(product);
        }


        [HttpGet]
        [Route("Admin/ProductManager/Edit/{id}")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.SingleOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Domain", product.CategoryId);
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division", product.DistrictId);
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Email", product.SellerId);
            return View(product);
        }


        [HttpPost]
        public IActionResult Edit(int? id, Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Products.Update(product);
                    _context.SaveChanges();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "Id", "Domain", product.CategoryId);
            ViewData["DistrictId"] = new SelectList(_context.Districts, "Id", "Division", product.DistrictId);
            ViewData["SellerId"] = new SelectList(_context.Sellers, "Id", "Email", product.SellerId);
            return View(product);
        }



        [Route("Admin/ProductManager/DeleteConfirmed/{id}")]
        public IActionResult DeleteConfirmed(int? id)
        {
            if (id == null)
            {
                NotFound();
            }

            var product = _context.Products.SingleOrDefault(m => m.Id == id);
            _context.Products.Remove(product);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(long id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

FreshMart/Areas/Admin/Views/ProductManager/Details.cshtml
@model FreshMart.Models.Product

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Products
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Hover Data Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Price</th>
                                    <th>District</th>
                                    <th>Seller Name</th>
                                    <th>Take Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr>
                                    <td>@Model.Title</td>
                                    <td>@Model.Price</td>
                                    <td>@Model.District.Name</td>
                                    <td>@Model.Seller.Name</td>


                                    <td>
                                        @Html.ActionLink("Edit", "Edit", "ProductManager", new { id = Model.Id }) |
                                        @Html.ActionLink("Details", "Details", "ProductManager", new { id = Model.Id }) |
                                        @Html.ActionLink("Delete", "Delete", "ProductManager", new { id = Model.Id })
                                    </td>


                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>

FreshMart/Areas/Admin/Views/ProductManager/Edit.cshtml
@model FreshMart.Models.Product

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}



<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Edit Product
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Update Product</h3>
                    </div>
                    <!-- /.box-header -->
                    @using (Html.BeginForm("Edit", "ProductManager", new { id = Model.Id }, FormMethod.Post))
                    {
                        <div class="box-body">
                            @Html.HiddenFor(c => c.Id)
                            <div class="form-group">
                                @Html.LabelFor(c => c.Title, new { @class = "control-label" })
                                @Html.TextBoxFor(c => c.Title, new { @class = "form-control" })
                            </div>

                            @Html.HiddenFor(c => c.Id)
                            @Html.HiddenFor(c => c.SellerId)
                            @Html.HiddenFor(c => c.Unit)
                            @Html.HiddenFor(c => c.IsPublished)
                            @Html.HiddenFor(c => c.ImagePath)
                            @Html.HiddenFor(c => c.DistrictId)
                            @Html.HiddenFor(c => c.CategoryId)
                            @Html.HiddenFor(c => c.CreatedAt)


                            <div class="form-group">
                                @Html.LabelFor(c => c.Price, new { @class = "control-label" })
                                @Html.TextBoxFor(c => c.Price, new { @class = "form-control" })

                            </div>
                            <div class="form-group">
                                @Html.LabelFor(c => c.Description, new { @class = "control-label" })
                                @Html.TextBoxFor(c => c.Description, new { @class = "form-control" })
                            </div>



                            <div class="form-group">
                                @Html.LabelFor(c => c.ItemInStock, new { @class = "control-label" })
                                @Html.TextBoxFor(c => c.ItemInStock, new { @class = "form-control" })

                            </div>

                            <div class="form-group">
                                @Html.LabelFor(c => c.OfferPrice, new { @class = "control-label" })
                                @Html.TextBoxFor(c => c.OfferPrice, new { @class = "form-control" })
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(c => c.OfferExpireDate, new { @class = "control-label" })
                                @Html.TextBoxFor(c => c.OfferExpireDate, new { @class = "form-control" })
                            </div>

                        </div>

                        <div class="box-footer">
                            <input type="submit" value="Save" class="btn btn-default" />

                        </div>
                    }

                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>

FreshMart/Areas/Admin/Views/ProductManager/Index.cshtml
@model IEnumerable<FreshMart.Models.Product>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_adminlayout.cshtml";
}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            All Products
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
            <li><a href="#">Tables</a></li>
            <li class="active">Data tables</li>
        </ol>
    </section>


    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">Product Table</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Title</th>
                                    <th>Price</th>
                                    <th>District</th>
                                    <th>Seller Name</th>
                                    <th>Category</th>
                                    <th>Take Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Title</td>
                                        <td>@item.Price</td>
                                        <td>@item.District.Name</td>
                                        <td>@item.Seller.Name</td>
                                        <td>@item.Category.Name</td>

                                        <td>
                                            @Html.ActionLink("Edit", "Edit", "ProductManager", new { id = item.Id }) |
                                            @Html.ActionLink("Details", "Details", "ProductManager", new { id = item.Id }) |
                                            @Html.ActionLink("Delete", "DeleteConfirmed", "ProductManager", new { id = item.Id })
                                        </td>

                                    </tr>
                                }

                            </tbody>

                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </section>
    <!-- /.content -->

</div>