FreshMart/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreshMart.Core;
using FreshMart.Database;
using FreshMart.Helper;
using FreshMart.Models;
using FreshMart.ViewModels;
using FreshMart.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace FreshMart.Controllers
{

    public class CartController : Controller
    {
        //AppUser appUser;

        private readonly AppDbContext _context;
        private int cartCount;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly IProductService _productService;
        public CartController(AppDbContext con, IHttpContextAccessor hca, IProductService productService)
        {
            _context = con;
            _httpContextAccessor = hca;
            _productService = productService;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
        }


        [Route("/Cart")]
        public async Task<ActionResult> Cart()
        {
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                ViewBag.Message = "Your Cart Is Empty";
                this.cartCount = 0;
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;
                this.cartCount = cart.Count;
                ViewBag.total = cart.Sum(c => c.Product.Price * c.Quantity);
            }
            var viewmodel = await _productService.GetProductViewModelAsync();

            ViewBag.CartCount = this.cartCount;
            return View(viewmodel);
        }


        [Route("Cart/addtocart/{id}")]
        public ActionResult AddToCart(long id)
        {
            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                var cart = new List<CartItem>();
                var item = new CartItem
                {
                    Product = _context.Products.Where(x => x.Id == id).Include(x => x.Photo).AsEnumerable().Select(x =>
                    {
                        if (x.Photo != null)
                        {
                            x.Photo.Path = "https://localhost:44318" + x.Photo.Path;
                        }
                        return x;
                    }).FirstOrDefault(),
                    Quantity = 1
                };
                cart.Add(item);

                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
                var sessiondata = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                int index = Exists(cart, id);
                if (index == -1)
                {
                    var item = new CartItem
                    {
                        Product = _context.Products.Where(x => x.Id == id).Include(x => x.Photo).AsEnumerable().Select(x =>
                       {
                           if (x.Photo != null)
                           {
                               x.Photo.Path = "https://localhost:44318" + x.Photo.Path;
                           }
                           return x;
                       }).FirstOrDefault(),
                        Quantity = 1,

                    };
                    cart.Add(item);
                }
                else
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }

            return RedirectToAction(nameof(Cart));
        }

        [Route("Cart/RemoveItem/{id}")]
        public ActionResult RemoveItem(long id)
        {

            var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);

            return RedirectToAction(nameof(Cart));
        }

        //local function start
        private int Exists(List<CartItem> cart, long id)
        {
            for (int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id == id)
                {
                    return i;
                }
            }
            return -1;
        }
        //local function end

    }
}

FreshMart/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FreshMart.Core;
using FreshMart.Database;
using FreshMart.Helper;
using FreshMart.Models;
using FreshMart.ViewModels;
using FreshMart.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FreshMart.Core.Utilities;

namespace FreshMart.Controllers
{
    //    [Authorize]
    public class OrderController : Controller
    {

        //AppUser appUser;

        private readonly AppDbContext _context;
        private int cartCount;
        private IHttpContextAccessor _httpContextAccessor;
        private readonly UserManager<AppUser> _userManager;

        public OrderController(AppDbContext con,
            IHttpContextAccessor hca,
            UserManager<AppUser> userManager)
        {
            _context = con;
            _httpContextAccessor = hca;
            _userManager = userManager;
        }

        protected override void Dispose(bool disposing)
        {
            _context.Dispose();
            //var b = User.Identity.Name.ToString();

        }


        [HttpGet]
        [Route("Order/Checkout")]
        public ActionResult Checkout()
        {

            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                ViewBag.Message = "Your Cart Is Empty";
                this.cartCount = 0;
                return RedirectToAction("cart", "Cart");
            }
            else
            {
                var cart = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");
                ViewBag.cart = cart;

                this.cartCount = cart.Count;
                ViewBag.total = cart.Sum(c => c.Product.Price * c.Quantity);
            }
            //Cart facts here end.................

            var districts = _context.Districts.ToList();
            var categories = _context.Categories.ToList();
            var domains = _context.Categories.Where(x => x.ParentId != null).Select(c => c.Parent.Name).Distinct().ToList();
            CartService cs = new CartService(_httpContextAccessor, _context);
            var totalPrice = cs.GetCartTotalPrice();
            var Count = cs.GetCartCount();



            var viewmodel = new OrderViewModel();

            viewmodel.District = districts;

            viewmodel.Category = categories;
            viewmodel.DistinctCat = domains;

            var customer = _context.Customers.Where(c => c.Email == User.Identity.Name);
            if (customer.SingleOrDefault() != null)
            {
                viewmodel.Customer = customer.SingleOrDefault();
            }

            if (User.Identity.Name != null)
            {
                ViewBag.Email = User.Identity.Name;
                viewmodel.Order = new Order
                {
                    Email = User.Identity.Name
                };
            }
            else
            {
                ViewBag.Email = null;
            }

            viewmodel.CartCount = Count;
            viewmodel.TotalPrice = totalPrice;
            viewmodel.Sellers = _context.Sellers.ToList();

            return View(viewmodel);
        }

        [HttpPost]
        public async Task<ActionResult> Checkout(OrderViewModel ovModel)
        {

            if (SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart") == null)
            {
                return RedirectToAction("Index", "Products");
            }


            Customer customer = new Customer();
            var customerExisted = _context.Customers.Where(c => c.Email == ovModel.Order.Email).AsNoTracking().FirstOrDefault();
            if (customerExisted == null)
            {
                //nw user
                var user = new AppUser
                {
                    Email = ovModel.Order.Email,
                    UserName = ovModel.Order.Email
                };
                var res = await _userManager.CreateAsync(user);
                if (res.Succeeded)
                {
                    var cust = new Customer
                    {
                        Id = NumberUtilities.GetUniqueNumber(),
                        Name = ovModel.Order.Name,
                        Email = ovModel.Order.Email,
                        Phone = ovModel.Customer.Phone,
                        UserId = user.Id
                    };
                    await _context.Customers.AddAsync(cust);
                    await _context.SaveChangesAsync();
                    customer = cust;
                }
            }
            else
            {
                customer = _context.Customers.Find(ovModel.Customer.Id);
            }

            var order = new Order
            {
                Id = NumberUtilities.GetUniqueNumber(),
                Name = customer.Name,
                Email = customer.Email,
                //fixed portion
                ShippingAddress = ovModel.Order.ShippingAddress,
                PostalCode = ovModel.Order.PostalCode,
                StreetNo = ovModel.Order.StreetNo,
                CustomerId = customer.Id,
                TotalPrice = ovModel.TotalPrice,
                OrderDate = DateTime.Now,
                AccountNo = ovModel.Order.AccountNo,
                TransactionId = ovModel.Order.TransactionId
            };

            _context.Orders.Add(order);
            _context.SaveChanges();


            var cartList = SessionHelper.GetObjectFromJson<List<CartItem>>(HttpContext.Session, "cart");

            ViewBag.total = cartList.Sum(c => c.Product.Price * c.Quantity);

            foreach (var item in cartList)
            {
                var order_product = new ProductOrder
                {
                    Id = NumberUtilities.GetUniqueNumber(),
                    OrderId = order.Id,
                    ProductId = item.Product.Id,
                    NumberOfProduct = item.Quantity
                };

                _context.ProductOrders.Add(order_product);
                _context.SaveChanges();


                var quantity = _context.Products.Where(c => c.Id == item.Product.Id).SingleOrDefault();
                if (quantity != null)
                {
                    var pro = _context.Products.Find(item.Product.Id);
                    pro.ItemInStock = pro.ItemInStock - order_product.NumberOfProduct;

                    _context.Products.Update(pro);
                    _context.SaveChanges();
                }
            }
            //clear the session now
            HttpContext.Session.Clear();

            var agents = _context.Agents.Where(c => c.User.DistrictId == customer.User.DistrictId).ToList();
            var random = new Random();
            var index = random.Next(0, agents.Count);
            var agent = agents[index];

            var agentorder = new AgentOrder
            {
                Id = NumberUtilities.GetUniqueNumber(),
                AgentId = agent.Id,
                OrderId = order.Id,
                IsPaid = false,
                IsOnRoute = false,
                IsFullyCompleted = false
            };

            _context.AgentOrders.Add(agentorder);
            _context.SaveChanges();



            TempData["orderSuccess"] = "Your order has been placed successfully!";
            return RedirectToAction("Checkout");
        }

    }
}

FreshMart/Views/Cart/Cart.cshtml
@model FreshMart.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Cart";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

@if (ViewBag.CartCount > 0)
{
    <h2 class="text-center" style="margin-bottom: 20px;margin-top: 20px">Cart</h2>
}

@if (TempData["orderSuccess"] != null)
{
    <h3 class="text-center" style="margin-bottom:50px">@TempData["orderSuccess"]</h3>
}

@if (ViewBag.CartCount == 0)
{
    <h1 class="text-center" style="margin-bottom:20px;margin-top:20px">Your cart is empty.</h1>
}
else
{
    <div class="checkout">
        <div class="container">
            <h3>Your shopping cart contains: <span style="color: coral; font-size: 25px;">@Model.CartCount </span>Products</h3>

            <div style='margin: 0 auto;text-align: center;margin-top: 5px;'>
                <script>
                    var allowedNumberOfEboundDynamicAdds = 4;
                    var sizesEboundDynamicAdsDesktop = ['728x90'];
                    var sizesEboundDynamicAdsTablet = ['728x90'];
                    var sizesEboundDynamicAdsMobile = ['320x100'];
                    eboundAdsTagByDevice(sizesEboundDynamicAdsDesktop, sizesEboundDynamicAdsTablet, sizesEboundDynamicAdsMobile, 'ebound_header_tag');

                    if (typeof user_tag_config == 'undefined') {
                        var user_tag_config = {};
                    }
                    user_tag_config['ebound_header_tag'] = {};
                    user_tag_config['ebound_header_tag']['desktop'] = {};
                    user_tag_config['ebound_header_tag']['desktop']['cpm'] = '';
                    user_tag_config['ebound_header_tag']['desktop']['adsCode'] = '';
                    user_tag_config['ebound_header_tag']['tablet'] = {};
                    user_tag_config['ebound_header_tag']['tablet']['cpm'] = '';
                    user_tag_config['ebound_header_tag']['tablet']['adsCode'] = '';
                    user_tag_config['ebound_header_tag']['mobile'] = {};
                    user_tag_config['ebound_header_tag']['mobile']['cpm'] = '';
                    user_tag_config['ebound_header_tag']['mobile']['adsCode'] = '';
                </script>
            </div>

            <div class="checkout-right">
                @using (Html.BeginForm("UpdateItem", "cart"))
                {
                    <table class="timetable_sub">
                        <thead>
                            <tr>
                                <th>SL No.</th>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Product Name</th>
                                <th>Price</th>
                                <th>Remove</th>
                            </tr>
                        </thead>
                        @{
                            int count = 1;
                        }

                        @foreach (var items in @ViewBag.cart)
                        {
                            <tr class="rem1">
                                <td class="invert">@count</td>
                                <td class="invert-image">
                                    <img style="max-height:60px; max-width:60px;" src="@items.Product.Photo?.Path" alt=" " class="img-responsive" />
                                </td>
                                <td class="invert">
                                    <div class="quantity">
                                        <div class="quantity-select">
                                            <div class=""><span>@items.Quantity</span></div>
                                        </div>
                                    </div>
                                </td>
                                <td class="invert">@items.Product.Title</td>
                                <td class="invert">@items.Product.Price</td>
                                <td class="invert">
                                    <div class="rem">
                                        <a asp-controller="Cart" asp-action="RemoveItem" asp-route-id="@items.Product.Id" class="close1"></a>
                                    </div>
                                </td>
                            </tr>
                            count++;
                        }

                        @if (ViewBag.total == null)
                        {
                            <tr class="rem1" style="height:70px;">
                                <td class="invert glyphicon-bold">Total Price : $0 </td>
                            </tr>
                        }
                        else
                        {
                            <tr class="rem1" style="height:40px; height:70px;">
                                <td class="invert">Total Price : $@ViewBag.total </td>
                            </tr>
                        }
                    </table>
                }
            </div>

            <div class="checkout-left">
                <a asp-controller="Products" asp-action="Index" class="checkout-left-basket">
                    <h4><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span>Continue Shopping</h4>
                </a>
                <div class="checkout-right-basket">
                    <a asp-controller="Order" asp-action="Checkout">
                        <span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>Go For Checkout
                    </a>
                </div>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
}